name: Build and Release

on:
  push:
    tags:
      - 'v*' # Ворклоу запустится, если вы запушите тег, начинающийся на 'v' (например, v1.0.0)

jobs:
  build-and-release:
    name: Build and Create Release
    runs-on: windows-latest # Windows Forms собирается на Windows

    permissions:
      contents: write # Права для создания релиза

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Publish App (x64)
        run: dotnet publish -c Release -r win-x64 --self-contained false -p:PublishSingleFile=true -o ./publish_output_x64

      - name: Publish App (x86)
        run: dotnet publish -c Release -r win-x86 --self-contained false -p:PublishSingleFile=true -o ./publish_output_x86

      - name: Create Zip Archive (x64)
        run: Compress-Archive -Path ./publish_output_x64/* -DestinationPath HotKeyHelper-win-x64.zip

      - name: Create Zip Archive (x86)
        run: Compress-Archive -Path ./publish_output_x86/* -DestinationPath HotKeyHelper-win-x86.zip

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            HotKeyHelper-win-x64.zip
            HotKeyHelper-win-x86.zip
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
